/*
 
 jQuery Tools 1.2.3 Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date:    Mon Jun 7 13:43:53 2010 +0000 
*/
(function(a){function s(c,d){var e=this,f=c.add(e),h=a(window),j,g,l,m=a.tools.expose&&(d.mask||d.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var t=d.target||c.attr("rel");g=t?a(t):c;if(!g.length)throw"Could not find Overlay: "+t;c&&c.index(g)==-1&&c.click(function(k){e.load(k);return k.preventDefault()});a.extend(e,{load:function(k){if(e.isOpened())return e;var p=b[d.effect];if(!p)throw'Overlay: cannot find effect : "'+d.effect+
'"';d.oneInstance&&a.each(n,function(){this.close(k)});k=k||a.Event();k.type="onBeforeLoad";f.trigger(k);if(k.isDefaultPrevented())return e;l=true;m&&a(g).expose(m);var q=d.top,u=d.left,v=g.outerWidth({margin:true}),w=g.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((h.height()-w)/2,0):parseInt(q,10)/100*h.height();if(u=="center")u=Math.max((h.width()-v)/2,0);p[0].call(e,{top:q,left:u},function(){if(l){k.type="onLoad";f.trigger(k)}});m&&d.closeOnClick&&a.mask.getMask().one("click",
e.close);d.closeOnClick&&a(document).bind("click."+o,function(r){a(r.target).parents(g).length||e.close(r)});d.closeOnEsc&&a(document).bind("keydown."+o,function(r){r.keyCode==27&&e.close(r)});return e},close:function(k){if(!e.isOpened())return e;k=k||a.Event();k.type="onBeforeClose";f.trigger(k);if(!k.isDefaultPrevented()){l=false;b[d.effect][1].call(e,function(){k.type="onClose";f.trigger(k)});a(document).unbind("click."+o).unbind("keydown."+o);m&&a.mask.close();return e}},getOverlay:function(){return g},
getTrigger:function(){return c},getClosers:function(){return j},isOpened:function(){return l},getConf:function(){return d}});a.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(k,p){a.isFunction(d[p])&&a(e).bind(p,d[p]);e[p]=function(q){a(e).bind(p,q);return e}});j=g.find(d.close||".close");if(!j.length&&!d.close){j=a('<a class="close"></a>');g.prepend(j)}j.click(function(k){e.close(k)});d.load&&e.load()}a.tools=a.tools||{version:"1.2.3"};a.tools.overlay={addEffect:function(c,
d,e){b[c]=[d,e]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!a.browser.msie||a.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"40%"}};var n=[],b={};a.tools.overlay.addEffect("default",function(c,d){var e=this.getConf(),f=a(window);if(!e.fixed){c.top+=f.scrollTop();c.left+=f.scrollLeft()}c.position=e.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(e.speed,d)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});a.fn.overlay=function(c){var d=this.data("overlay");if(d)return d;if(a.isFunction(c))c={onBeforeLoad:c};c=a.extend(true,{},a.tools.overlay.conf,c);this.each(function(){d=new s(a(this),c);n.push(d);a(this).data("overlay",d)});return c.api?d:this}})(jQuery);(function(a){function s(){this.averageRating=this.numOfRatings=this.numOfComments=0;this.textareaIsDefault=true;this.editCommentRelatedComment=this.editCommentName=this.savedCommentContent=this.pageToDelete=this.replyCommentName=this.currentView=this.savedStructure=this.overlayName=this.currentDomain=this.currentUserPassword=this.currentUserName=this.currentPageContent=this.currentPageName=this.currentWikiPath=this.currentWikiurl=this.XMLResult=this.internalCall=this.ratingValue=null;this.editMode=
false;this.editRatingValue=null;this.processForm=function(){a("#collabComForm *:input").attr("disabled","disabled");if(typeof this.pendingIndicatorCF==="undefined"||this.pendingIndicatorCF===null)this.pendingIndicatorCF=new n(a("#collabComFormTextarea"));this.pendingIndicatorCF.show();var b=new Date;b=mw.config.get("wgPageName")+"_"+b.getTime();var c="";if(this.ratingValue!==null)c="|CommentRating="+this.ratingValue;var d=a("#collabComFormTextarea").val()?a("#collabComFormTextarea").val():"";if(d.length===
0||this.textareaIsDefault){this.pendingIndicatorCF.hide();a("#collabComFormMessage").attr("class","failure");a("#collabComFormMessage").html(ceLanguage.getMessage("ce_invalid"));a("#collabComFormMessage").show("slow");a("#collabComForm *:input").removeAttr("disabled");return false}else a("#collabComFormMessage").hide("slow");d=d.replace(/&/g,"&amp;");d=d.replace(/</g,"&lt;");d=d.replace(/>/g,"&gt;");d=this.textEncode(d);var e="|AttachedArticles="+(a("#collabComFormFileAttach").val()?a("#collabComFormFileAttach").val():
""),f="";f=wgUserName!==null&&wgCEUserNS!==null?"|CommentPerson="+wgCEUserNS+":"+wgUserName:"|CommentPerson=";var h="";if(this.replyCommentName!==null)h="|CommentRelatedComment="+this.replyCommentName;c="{{Comment"+f+"|CommentRelatedArticle="+mw.config.get("wgPageName")+c+h+"|CommentDatetime=##DATE##|CommentContent="+d+e+"|}}";this.currentPageName=escape(b);this.currentPageContent=escape(c);sajax_do_call("cef_comment_createNewPage",[this.currentPageName,this.currentPageContent],this.processFormCallback.bindToFunction(this));
return false};this.processFormCallback=function(b){var c=this.XMLResult=CollaborationXMLTools.createDocumentFromString(b.responseText);b=c.getElementsByTagName("value")[0];c=c.getElementsByTagName("message")[0].firstChild.nodeValue;this.pendingIndicatorCF.hide();a("#collabComForm").get(0).reset();a("#collabComForm").hide();a("#collabComForm *:input").removeAttr("disabled");var d=a("#collabComFormMessage");d.show();if(b.nodeType===1){b=b.firstChild.nodeValue;if(b==="0"){d.attr("class","success").html(c+
ceLanguage.getMessage("ce_reload"));a("<span>",{id:"collabComFormPending",html:"&nbsp;"}).appendTo(d);if(typeof this.pendingIndicatorMsg==="undefined"||this.pendingIndicatorMsg===null)this.pendingIndicatorMsg=new n(a("#collabComFormPending"));this.pendingIndicatorMsg.show();b=window.location.search;if(b.indexOf("action=purge")!==-1)window.location.reload();else window.location.href=b.indexOf("?")!==-1?window.location.href.concat("&action=purge"):window.location.href.concat("?action=purge");return true}else if(b===
"1"||b==="2"){this.pendingIndicatorCF.hide();d.attr("class","failure").html(c)}}return false};this.deleteComment=function(b,c){var d="",e=a("#"+b+" > .collabComPlain").html(),f=false,h=a("#"+c),j=false,g;this.overlayName=c;this.pageToDelete=b;a("*:input",h).attr("disabled","disabled");if(a(".ceOverlayFullDeleteCheckbox:checked",h).length===1){f=true;d=ceLanguage.getMessage("ce_full_deleting");j=true;for(g=a("#"+b).next(".comRearranged");j;){if(g.length===0)j=false;else e+=", "+a(".collabComPlain",
g).html();g=g.next(".comRearranged")}}else d=ceLanguage.getMessage("ce_deleting");a(".ceOverlayDetails",h).html(d);d=a("<span>",{id:"collabComDelPending",html:"&nbsp;"});a(".ceOverlayDetails",h).append(d);if(typeof this.pendingIndicatorDel==="undefined"||this.pendingIndicatorDel===null)this.pendingIndicatorDel=new n(a("#collabComDelPending"));this.pendingIndicatorDel.show();f?sajax_do_call("cef_comment_fullDeleteComments",[escape(e)],this.deleteCommentCallback.bindToFunction(this)):sajax_do_call("cef_comment_deleteComment",
[escape(e)],this.deleteCommentCallback.bindToFunction(this))};this.deleteCommentCallback=function(b){var c=this.XMLResult=CollaborationXMLTools.createDocumentFromString(b.responseText),d=c.getElementsByTagName("value")[0];b=c.getElementsByTagName("message")[0].firstChild.nodeValue;c.getElementsByTagName("article");var e="#"+this.pageToDelete;c=a("<div>",{id:"collabComEditFormMessage"});a(e).before(c);if(d.nodeType===1){d=d.firstChild.nodeValue;this.pendingIndicatorDel.hide();if(d==="0"){b+=ceLanguage.getMessage("ce_reload");
a("#"+this.overlayName).hide();c.addClass("success");c.html(b);b=a("<span>",{id:"collabComDelPending",html:"&nbsp;"}).appendTo(c);if(typeof this.pendingIndicatorDel2==="undefined"||this.pendingIndicatorDel2===null)this.pendingIndicatorDel2=new n(b);this.pendingIndicatorDel2.show();b=window.location.search;if(b.indexOf("action=purge")!==-1)window.location.reload();else window.location.href=b.indexOf("?")!==-1?window.location.href.concat("&action=purge"):window.location.href.concat("?action=purge");
return true}else{if(d==="1"||d==="2"){c.addClass("failure");c.html(b)}return false}}return false};this.editCommentForm=function(b){var c,d,e,f,h,j,g,l,m,o="";this.editCommentName=b;d="#"+b;this.editCommentRelatedComment=a(d+" .collabComResInfoSuper").html();if(this.editMode)return false;this.editMode=true;e=a(d);f=a(d+" .collabComResText").html();e.css("background-color","#F2F2F2");this.savedCommentContent=f;f=this.textDecode(f);a(d+" .collabComResText").toggle();a(d+" .collabComResRight").css("width",
"85%");if(typeof wgCEEnableRating!=="undefined"){if(c=a(d+" .collabComResRatingIcon img").attr("src")){if(c.match("Bad")){h=-1;j=true}if(c.match("Neutral")){h=0;j=true}if(c.match("Good")){h=1;j=true}}e=document.createTextNode(ceLanguage.getMessage("ce_edit_rating_text"));c=document.createTextNode(ceLanguage.getMessage("ce_edit_rating_text2"));g=document.createTextNode(":");l=a("<span>",{"class":"collabComFormGrey"});l.append(a(c));c=a("<div>",{id:"collabComEditFormRating"});c.append(a(e));c.append(l);
c.append(a(g));e=a("<span>",{id:"collabComEditFormRadioButtons"});a("<img>",{id:"collabComEditFormRating1","class":"collabComEditFormRatingImg",src:wgCEScriptPath+"/skins/Comment/icons/bad_inactive.png",click:function(){ceCommentForm.switchEditRating("#collabComEditFormRating1",-1)}}).appendTo(e);a("<img>",{id:"collabComEditFormRating2","class":"collabComEditFormRatingImg",src:wgCEScriptPath+"/skins/Comment/icons/neutral_inactive.png",click:function(){ceCommentForm.switchEditRating("#collabComEditFormRating2",
0)}}).appendTo(e);a("<img>",{id:"collabComEditFormRating3","class":"collabComEditFormRatingImg",src:wgCEScriptPath+"/skins/Comment/icons/good_inactive.png",click:function(){ceCommentForm.switchEditRating("#collabComEditFormRating3",1)}}).appendTo(e);c.append(e)}f=a("<textarea>",{id:"collabComEditFormTextarea",rows:"5",value:f});if(typeof wgCEEnableAttachments!==undefined){g=document.createElement("input");g.setAttribute("type","text");m=a(g).addClass("wickEnabled").attr({pastens:"true",id:"collabComEditFormFileAttach"}).val(a(d+
" .collabComResFileAttachSaved").html());if(typeof wgCEEditUploadURL!=="undefined"){o=a("<span>",{id:"collabComEditFormFileAttachLink"});a("<a>",{id:"collabComEditFormFileAttach","class":"rmAlink",title:"Upload file",href:wgCEEditUploadURL,text:"Upload file"}).appendTo(o)}}e=a("<div>");g=document.createElement("input");g.setAttribute("type","button");a(g).attr("id","collabComEditFormSubmit").val(ceLanguage.getMessage("ce_edit_button")).click(function(){ceCommentForm.editExistingComment()}).appendTo(e);
a("<span>",{id:"collabComEditFormCancel",text:" | "+ceLanguage.getMessage("ce_cancel_button"),click:function(){ceCommentForm.cancelCommentEditForm(b)}}).appendTo(e);g=a("<div>",{id:"collabComEditFormMessage",style:"display: none"});a(d+" .collabComResText").html("");typeof c!=="undefined"&&c!==null&&a(d+" .collabComResText").append(c);a(d+" .collabComResText").append(f);a(d+" .collabComResText").append(m);a(d+" .collabComResText").append(o);a(d+" .collabComResText").append(e);a(d+" .collabComResText").append(g);
j&&ceCommentForm.switchEditRating("#collabComEditFormRating"+(parseInt(h)+2),h);a(d+" .collabComEditCancel").show();a(d+" .collabComResText").show();a(d+" .collabComEdit").hide();a(d+" .collabComReply").hide();return true};this.editExistingComment=function(){a("#"+this.editCommentName+" *:input").attr("disabled","disabled");if(typeof this.pendingIndicatorEF==="undefined"||this.pendingIndicatorEF===null)this.pendingIndicatorEF=new n(a("#collabComEditFormTextarea"));this.pendingIndicatorEF.show();var b=
"";if(this.editRatingValue!==null)b="|CommentRating="+this.editRatingValue;var c=a("#collabComEditFormTextarea").val()?a("#collabComEditFormTextarea").val():"";c.replace(/&/g,"&amp;");c.replace(/</g,"&lt;");c.replace(/>/g,"&gt;");c=this.textEncode(c);var d=a(".collabComResUsername > a",a("#"+this.editCommentName)).html();if(d){d=d.split(":");d=d.pop();d="|CommentPerson="+wgCEUserNS+":"+d}else d="";var e="";if(this.editCommentRelatedComment!==null&&this.editCommentRelatedComment!=="")e="|CommentRelatedComment="+
this.editCommentRelatedComment;var f="";f=mw.config.get("wgUserName")!==null&&wgCEUserNS!==null?"|CommentLastEditor="+wgCEUserNS+":"+mw.config.get("wgUserName"):"|CommentLastEditor=";var h="|AttachedArticles="+(a("#collabComEditFormFileAttach").val()?a("#collabComEditFormFileAttach").val():"");b="{{Comment"+d+"|CommentRelatedArticle="+mw.config.get("wgPageName")+b+"|CommentDatetime=##DATE##|CommentContent="+c+e+f+h+"|}}";this.currentPageName=escape(a(".collabComPlain",a("#"+this.editCommentName)).html());
this.currentPageContent=escape(b);sajax_do_call("cef_comment_editPage",[this.currentPageName,this.currentPageContent],this.editExistingCommentCallback.bindToFunction(this));return true};this.editExistingCommentCallback=function(b){var c="#"+this.editCommentName;b=this.XMLResult=CollaborationXMLTools.createDocumentFromString(b.responseText);var d=b.getElementsByTagName("value")[0];b=b.getElementsByTagName("message")[0].firstChild.nodeValue;this.pendingIndicatorEF.hide();if(d.nodeType===1){d=d.firstChild.nodeValue;
var e=a("<div>",{id:"collabComEditFormMessage"});a(c).before(e);if(d==="0"){e.show();e.addClass("success");e.html(b+ceLanguage.getMessage("ce_reload"));a("<span>",{id:"collabComEditFormPending",html:"&nbsp;"}).appendTo(e);if(typeof this.pendingIndicatorMsg==="undefined"||this.pendingIndicatorMsg===null)this.pendingIndicatorMsg=new n(a("#collabComEditFormPending"));this.pendingIndicatorMsg.show();c=window.location.search;if(c.indexOf("action=purge")!==-1)window.location.reload();else window.location.href=
c.indexOf("?")!==-1?window.location.href.concat("&action=purge"):window.location.href.concat("?action=purge");return true}else if(d==="1"||d==="2"){e.addClass("failure");e.html(b);a(c+" *:input").removeAttr("disabled")}}return false};this.cancelCommentEditForm=function(b){this.editMode=false;this.editRatingValue=this.editCommentRelatedComment=this.editCommentName=null;b="#"+b;a(b).css("background-color","");a(b+" .collabComResText").toggle();a(b+" .collabComResText").html(this.savedCommentContent);
a(b+" .collabComResText").toggle();a(b+" .collabComResRight").css("width","");a(b+" .collabComEditCancel").hide();a(b+" .collabComEdit").toggle();a(b+" .collabComReply").show();return true};this.replyCommentForm=function(b){b=a("#"+b);this.replyCommentName=a(".collabComPlain",b).html();var c=a("#collabComForm");a("#collabComFormResetbuttonID").bind("click",function(){c.hide();c.css("marginLeft","");a("#collabComFormHeader").append(c)});var d=b.css("margin-left");if(typeof d!=="undefined"){d=parseInt(d)+
30;c.css("marginLeft",d)}else c.css("marginLeft","30px");b.after(c);c.show()};this.textEncode=function(b){b=b.replace(/:/g,"&#58;");b=b.replace(/\{/g,"&#123;");b=b.replace(/\{/g,"&#123;");b=b.replace(/\[/g,"&#91;");b=b.replace(/\]/g,"&#93;");b=b.replace(/\//g,"&#47;");b=b.replace(/\\/g,"&#92;");b=b.replace(/(\r\n|\r|\n)/g,"<br />");b=b.split("<br />");for(var c=0;c<=b.length-1;c++)b[c]=b[c].replace(/^\s/,"&nbsp;");return b=b.join("<br />")};this.textDecode=function(b){b=b.replace(/<br\/>|<br \/>|<br>/gi,
"\n");b=b.replace(/&nbsp;/g," ");b=b.replace(/&#58;/g,":");b=b.replace(/&#123;/g,"}");b=b.replace(/&#123;/g,"{");b=b.replace(/&#91;/g,"[");b=b.replace(/&#93;/g,"]");b=b.replace(/&#47;/g,"/");return b=b.replace(/&#92;/g,"\\")};this.formReset=function(){this.textareaIsDefault=true;this.replyCommentName=null;if(this.ratingValue!==null){var b="#collabComFormRating"+String(this.ratingValue+2);a(b).attr("src",a(b).attr("src").replace(/_active/g,"_inactive"));this.ratingValue=null}a("#collabComForm").get(0).reset();
a("#collabComForm").toggle("slow")};this.selectTextarea=function(){this.textareaIsDefault&&a("#collabComFormTextarea").select()};this.textareaKeyPressed=function(){this.textareaIsDefault=false};this.switchRating=function(b,c){var d=a(b),e=wgCEScriptPath+"/skins/Comment/icons/",f="#collabComFormRating"+String(this.ratingValue+2);a(f).attr("src",a(f).attr("src").replace(/_active/g,"_inactive"));if(this.ratingValue==c){this.ratingValue=null;return true}switch(c){case -1:d.attr("src",e+"bad_active.png");
break;case 0:d.attr("src",e+"neutral_active.png");break;case 1:d.attr("src",e+"good_active.png");break}this.ratingValue=c;return true};this.switchEditRating=function(b,c){var d=a(b),e=wgCEScriptPath+"/skins/Comment/icons/",f="#collabComEditFormRating"+String(this.editRatingValue+2);a(f).attr("src",a(f).attr("src").replace(/_active/g,"_inactive"));if(this.editRatingValue==c){this.editRatingValue=null;return true}switch(c){case -1:d.attr("src",e+"bad_active.png");break;case 0:d.attr("src",e+"neutral_active.png");
break;case 1:d.attr("src",e+"good_active.png");break}this.editRatingValue=c;return true};this.toggleComments=function(){var b=a("#collabComToggle"),c=a("#collabComResults"),d="";d=c.css("display")==="block"?ceLanguage.getMessage("ce_com_show"):ceLanguage.getMessage("ce_com_hide");b.html(" | "+d);c.toggle("slow");a("#collabComFormToggle, #collabComViewToggle, #collabComFileToggle").toggle();return true};this.toggleView=function(){var b=parseInt(a("#collabComViewToggle option:selected").val());if(b===
this.currentView)return true;else if(b===0)this.showThreaded();else b===1&&this.showFlat();return true};this.toggleFileAttachment=function(b){typeof b!=="string"||b===""?a(".collabComResFileAttach").toggle("slow"):a(" .collanComResFileAttach",a("#"+b)).toggle("slow");return true};this.showFlat=function(){this.editMode&&this.cancelCommentEditForm(this.editCommentName);a("#collabComResults").html(a(this.savedStructure.html()));var b=a(".collabComRes");a.each(b,function(c,d){var e=a(d).attr("id");a(".collabComDel",
d).bind("click",function(){a("#"+e).css("background-color","#FAFAD2")});a(".collabComEdit",d).bind("click",function(){ceCommentForm.editCommentForm(e)});a(".collabComReply",d).bind("click",function(){ceCommentForm.replyCommentForm(e)})});this.currentView=1;this.bindOverlays();a("#collabComFileToggle > input").attr("checked")===false&&a(".collabComResFileAttach:first").filter(":visible")&&a(".collabComResFileAttach").hide();return true};this.showThreaded=function(){a(".collabComRes").each(function(b,
c){var d=a(".collabComResInfoSuper",c).html();if(d){var e=a("#"+d).css("margin-left"),f="30";if(typeof e!=="undefined")f=parseInt(e)+30;e=ceCommentForm.getLastChildComment(d);e!==d?a("#"+e).after(a(c)):a("#"+d).after(a(c));a(c).css("margin-left",f+"px");a(c).addClass("comRearranged")}});this.currentView=0;return true};this.getLastChildComment=function(b){var c;c=a(".comRearranged").filter(function(){return a(".collabComResInfoSuper",this).html()==b});if(c.length>0){c=c[c.length-1];return this.getLastChildComment(a(c).attr("id"))}else return b};
this.setCommentQuantities=function(){this.numOfComments=a(".collabComRes").length;this.numOfRatings=a(".collabComResRatingIcon").length;if(this.numOfRatings===0)return true;var b=0;a(".collabComResRatingIcon").each(function(){if(a("img",this).attr("src").indexOf("Bad")>=0)b--;else a("img",this).attr("src").indexOf("Good")>=0&&b++});this.averageRating=b/this.numOfRatings;return true};this.buildHeader=function(){this.setCommentQuantities();if(this.addHeaderText()===true){this.addCommentToggler();if(typeof wgCECommentsDisabled===
"undefined"||wgCECommentsDisabled===false)this.addFormToggler(true);this.addHeaderView();this.addFileToggler();this.addHeaderRating()}return true};this.addHeaderText=function(){return this.numOfComments>0?this.addExtendedHeaderText():this.addDefaultHeaderText()};this.addDefaultHeaderText=function(){this.addFormToggler(false);a("#collabComFormToggle").css("font-weight","bold");return false};this.addExtendedHeaderText=function(){a("<span>",{"class":"collabComInternComment",text:ceLanguage.getMessage("ce_com_ext_header")+
" ("+this.numOfComments+")"}).appendTo(".collabComInternHeader");return true};this.addCommentToggler=function(){a("<span>",{id:"collabComToggle",title:ceLanguage.getMessage("ce_com_toggle_tooltip"),text:" | "+ceLanguage.getMessage("ce_com_hide"),click:function(){ceCommentForm.toggleComments()}}).appendTo(".collabComInternHeader");return true};this.addFormToggler=function(b){var c="";c=typeof wgCEUserCanEdit!=="undefined"&&wgCEUserCanEdit===false?a("<span>",{id:"collabComFormToggle",style:"color: grey; cursor: default;",
title:ceLanguage.getMessage("ce_form_toggle_no_edit_tooltip"),text:(b?" | ":" ")+ceLanguage.getMessage("ce_com_default_header")}):a("<span>",{id:"collabComFormToggle",title:ceLanguage.getMessage("ce_form_toggle_tooltip"),text:(b?" | ":" ")+ceLanguage.getMessage("ce_com_default_header"),click:function(){a("#collabComForm").toggle("slow")}});a(".collabComInternHeader").append(a(c));return true};this.addHeaderView=function(){var b=a("<span>",{id:"collabComViewToggle",text:" | "+ceLanguage.getMessage("ce_com_view")+
": "}),c=a("<select>",{change:function(){ceCommentForm.toggleView()}});try{c.get(0).add(new Option(ceLanguage.getMessage("ce_com_view_threaded"),0,true,true),null)}catch(d){c.get(0).add(new Option(ceLanguage.getMessage("ce_com_view_threaded"),0,true,true))}try{c.get(0).add(new Option(ceLanguage.getMessage("ce_com_view_flat"),1),null)}catch(e){c.get(0).add(new Option(ceLanguage.getMessage("ce_com_view_flat"),1))}a(b).append(a(c));a(".collabComInternHeader").append(a(b));this.currentView=0;return true};
this.addFileToggler=function(){if(a(".collabComResFileAttach").length===0)return false;var b=a("<span>",{id:"collabComFileToggle",text:" | "+ceLanguage.getMessage("ce_com_file_toggle")+": "}),c=document.createElement("input");c.setAttribute("type","checkbox");a(c).change(function(){ceCommentForm.toggleFileAttachment()}).appendTo(a(b));a(".collabComResFileAttach:first").filter(":visible")&&a(c).attr("checked","checked");a(".collabComInternHeader").append(a(b));return true};this.addHeaderRating=function(){if(this.numOfRatings>
0){var b=a("<span>",{"class":"collabComInternAvg",text:ceLanguage.getMessage("ce_com_rating_text_short")+" ("+this.numOfRatings+") :",title:ceLanguage.getMessage("ce_com_rating_text")+" "+this.numOfRatings+" "+ceLanguage.getMessage("ce_com_rating_text2")}),c=a("<div>",{"class":"collabComInternRatingIcon"}),d=a("<img>"),e=wgCEScriptPath+"/skins/Comment/icons/";if(this.averageRating<-0.33)a(d).attr("src",e+"bad_active.png");else if(this.averageRating>=-0.33&&this.averageRating<=0.33)a(d).attr("src",
e+"neutral_active.png");else this.averageRating>0.33&&a(d).attr("src",e+"good_active.png");a(c).append(a(d));a(b).append(a(c));a(".collabComInternHeader").append(a(b))}return true};this.createOverlay=function(b,c){var d="overlay_"+b,e,f,h;f=a("<div>",{id:d,"class":"ceOverlay"});a("<div>",{"class":"ceOverlayDetails",text:ceLanguage.getMessage("ce_delete")}).appendTo(f);h=a("<div>",{"class":"ceOverlayFullDeleteDiv"}).appendTo(f);e=document.createElement("input");e.setAttribute("type","checkbox");a(e).addClass("ceOverlayFullDeleteCheckbox").attr("name",
"ceFullDelete").appendTo(h);e=document.createTextNode(ceLanguage.getMessage("ce_full_delete"));h.append(e);h=a("<div>",{"class":"ceOverlayCancelButtonDiv",click:function(){a("#"+c).css("background-color","")}});e=document.createElement("input");e.setAttribute("type","button");a(e).addClass("ceOverlayCancelButton close").val(ceLanguage.getMessage("ce_cancel_button")).appendTo(h);f.append(h);h=a("<div>",{"class":"ceOverlayDeleteButtonDiv",click:function(){ceCommentForm.deleteComment(escape(c),d)}});
e=document.createElement("input");e.setAttribute("type","button");a(e).addClass("ceOverlayDeleteButton").val(ceLanguage.getMessage("ce_delete_button")).appendTo(h);f.append(h);return f};this.bindOverlays=function(){var b=a(".collabComDel");a.each(b,function(c,d){var e=a(d).attr("id");a(d).overlay({api:true,onClose:function(){a(".collabComRes").removeClass("collabComDelSelected")},onBeforeLoad:function(){ceCommentForm.controlFullDeleteOptions(d,c,e.replace("ceDel",""))}})})};this.controlFullDeleteOptions=
function(b,c){typeof wgCEEnableFullDeletion!=="undefined"&&this.currentView===0&&typeof wgCEUserIsSysop!=="undefined"&&wgCEUserIsSysop!==null&&wgCEUserIsSysop!==false?a(".ceOverlayFullDeleteDiv",a("#overlay_"+c)).show():a(".ceOverlayFullDeleteDiv",a("#overlay_"+c)).hide();return true};this.preloadImages=function(){var b=[];b[0]=wgCEScriptPath+"/skins/Comment/icons/good_active.png";b[1]=wgCEScriptPath+"/skins/Comment/icons/neutral_active.png";b[2]=wgCEScriptPath+"/skins/Comment/icons/bad_active.png";
b[3]=wgCEScriptPath+"/skins/Comment/icons/Edit_button2_Active.png";b[4]=wgCEScriptPath+"/skins/Comment/icons/DeletedComment.png";for(i=0;i<b.length;i++)(new Image).src=b[i]}}function n(b){this.constructor=function(c){this.container=c;this.pendingIndicator=document.createElement("img");a(this.pendingIndicator).addClass("cependingElement");a(this.pendingIndicator).attr("src",mw.config.get("wgServer")+mw.config.get("wgScriptPath")+"/extensions/Collaboration/skins/Comment/icons/ajax-loader.gif");this.contentElement=
null};this.show=function(c,d){if(a("#content")!==null){var e=0;if(typeof d!=="undefined")switch(d){case "right":e=c?a(c).offsetWidth-16:a(this.container).offsetWidth-16;break;case "left":break}if(this.contentElement===null){this.contentElement=a("#content");this.contentElement.append(this.pendingIndicator)}var f=c?a("#container").offset():this.container.offset();this.pendingIndicator.style.left=e+f.left+"px";this.pendingIndicator.style.top=f.top-a(document).scrollTop()+"px";this.pendingIndicator.style.display=
"block";this.pendingIndicator.style.visibility="visible"}};this.showOn=function(c){b=c.offsetParent;a(b).insert({top:this.pendingIndicator});c=a(c).positionedOffset();this.pendingIndicator.style.left=c[0]+"px";this.pendingIndicator.style.top=c[1]+"px";this.pendingIndicator.style.display="block";this.pendingIndicator.style.visibility="visible";this.pendingIndicator.style.position="absolute"};this.hide=function(){a(this.pendingIndicator).hide()};this.remove=function(){a(this.pendingIndicator).remove()};
this.constructor(b)}a(document).ready(function(){window.ceCommentForm=new s});a(document).ready(function(){var b,c=a("#collabComForm").length>0?true:false;c&&ceCommentForm.preloadImages();var d=a(".collabComRes"),e=0;a.each(d,function(h,j){var g=a(j).attr("id");if(a(".collabComResDeletion",j).html()==="true"){a(".collabComResText",j).addClass("collabComDeleted");a(".collabComResPerson img",j).attr("src",wgCEScriptPath+"/skins/Comment/icons/DeletedComment.png");a(".collabComResRating",j).remove();
return true}if(a(".collabComEditInfo",j)){a(".collabComEditorPre",j).html(ceLanguage.getMessage("ce_edit_intro"));a(".collabComEditDatePre",j).html(ceLanguage.getMessage("ce_edit_date_intro"))}var l=a(".collabComResUsername > a",j).html();if(l){l=l.split(":");l=l.pop()}else l="";if(typeof wgCEUserIsSysop!=="undefined"&&wgCEUserIsSysop!==null&&wgCEUserIsSysop!==false||mw.config.get("wgUserName")!==null&&l===mw.config.get("wgUserName")){l=ceCommentForm.createOverlay(e,g);b=a("<span>",{id:"ceDel"+g,
"class":"collabComDel",title:ceLanguage.getMessage("ce_delete_title"),rel:"#overlay_"+e++,click:function(){a("#"+g).addClass("collabComDelSelected")}});a("<img>",{"class":"collabComDeleteImg",src:wgCEScriptPath+"/skins/Comment/icons/Delete_button.png"}).appendTo(b);a(".collabComResDate",j).after(b);a("#collabComResults").after(l);if(typeof wgCECommentsDisabled==="undefined"||wgCECommentsDisabled===false){b=a("<span>",{"class":"collabComEdit",title:ceLanguage.getMessage("ce_edit_title"),click:function(){ceCommentForm.editCommentForm(g)}});
a("<img>",{"class":"collabComEditImg",src:wgCEScriptPath+"/skins/Comment/icons/Edit_button2.png"}).appendTo(b);a(".collabComResDate",j).after(b);b=a("<span>",{"class":"collabComEditCancel",title:ceLanguage.getMessage("ce_edit_cancel_title"),click:function(){ceCommentForm.cancelCommentEditForm(g)}});a("<img>",{"class":"collabComEditCancelImg",src:wgCEScriptPath+"/skins/Comment/icons/Edit_button2_Active.png"}).appendTo(b);a(".collabComResDate",j).after(b);b.hide()}}if((typeof wgCECommentsDisabled===
"undefined"||wgCECommentsDisabled===false)&&typeof wgCEUserCanEdit==="undefined"){b=a("<span>",{"class":"collabComReply",title:ceLanguage.getMessage("ce_reply_title"),text:ceLanguage.getMessage("ce_com_reply"),click:function(){ceCommentForm.replyCommentForm(g)}}).insertAfter(a(".collabComResText",j));a("<img>",{"class":"collabComReplyImg",src:wgCEScriptPath+"/skins/Comment/icons/Reply_Comment.png"}).appendTo(b)}return true});if(c){ceCommentForm.buildHeader();ceCommentForm.savedStructure=a("#collabComResults").clone();
ceCommentForm.showThreaded();if(d.length!==0){c=a("#collabComToggle");d=a("#collabComResults");var f="";if(wgCEShowCommentsExpanded){f=ceLanguage.getMessage("ce_com_hide");d.show()}else{f=ceLanguage.getMessage("ce_com_show");d.hide();a("#collabComFormToggle, #collabComViewToggle, #collabComFileToggle").toggle()}c.html(" | "+f)}}});a(document).ready(function(){ceCommentForm.bindOverlays()});Function.prototype.bindToFunction=function(b){var c=this;return function(){return c.apply(b,arguments)}};window.C_bd=
new (function(){var b=navigator.userAgent.toLowerCase();this.isMozilla=(this.isGecko=b.indexOf("gecko")!=-1||b.indexOf("safari")!=-1)&&b.indexOf("gecko/")+14==b.length;this.isNS=this.isGecko?b.indexOf("netscape")!=-1:b.indexOf("mozilla")!=-1&&b.indexOf("spoofer")==-1&&b.indexOf("compatible")==-1&&b.indexOf("opera")==-1&&b.indexOf("webtv")==-1&&b.indexOf("hotjava")==-1;this.isIE=b.indexOf("msie")!=-1&&b.indexOf("opera")==-1&&b.indexOf("webtv")==-1;this.isOpera=b.indexOf("opera")!=-1;this.isSafari=
b.indexOf("safari")!=-1;this.isKonqueror=b.indexOf("konqueror")!=-1;this.isIcab=b.indexOf("icab")!=-1;this.isAol=b.indexOf("aol")!=-1;this.isWebtv=b.indexOf("webtv")!=-1;this.isGeckoOrOpera=this.isGecko||this.isOpera;this.isGeckoOrSafari=this.isGecko||this.isSafari});CollaborationXMLTools={};CollaborationXMLTools.createDocumentFromString=function(b){if(C_bd.isGeckoOrOpera)var c=(new DOMParser).parseFromString(b,"text/xml");else if(C_bd.isIE){c=new ActiveXObject("Microsoft.XMLDOM");c.async="false";
c.loadXML(b)}return c}})(jQuery);
